config/routes.rb
Shouter::Application.routes.draw do  
  root to: 'homes#show', via: :get
  resource :dashboard, only: [:show]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show] do
  	post 'follow' => 'following_relationships#create'
  	delete 'follow' => 'following_relationships#destroy'
  end

  resources :shouts, only: [:show]
  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
end

app/models/concerns/following.rb
module Concerns

	module Following
		extend ActiveSupport::Concern

		included do
			has_many :followed_user_relationships,
			foreign_key: :follower_id,
			class_name: 'FollowingRelationship'
			has_many :followed_users, through: :followed_user_relationships

			has_many :follower_relationships,
				foreign_key: :followed_user_id,
				class_name: 'FollowingRelationship'
			has_many :followers, through: :follower_relationships

			def following? user
		  	followed_user_ids.include? user.id
		  end

		  def follow user
		  	followed_users << user
		  end

		  def unfollow user
		  	followed_users.delete(user)
		  end
		end
	end

end

app/models/dashboard.rb
class Dashboard
	def initialize(user)
		@user = user
	end

	def new_text_shout
		TextShout.new
	end

	def new_photo_shout
		PhotoShout.new
	end

	def timeline
		Timeline.new(@user)
	end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
	has_attached_file :image, styles: {
		shout: "200x200>"
	}

	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/png", "image/jpeg"] }
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true
  default_scope -> { order('created_at DESC') }
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
end

app/models/timeline.rb
class Timeline
	include ActiveModel::Model

	def initialize user
		@user = user
	end

	def shouts
		Shout.where(user_id: shout_user_ids)
	end

	private
		def shout_user_ids
			[@user.id] + @user.followed_user_ids
		end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :shouts

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  include Concerns::Following

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Monban::ControllerHelpers
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  	@dashboard = Dashboard.new(current_user)
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
	def create
		current_user.follow(user)
		redirect_to user, notice: "Now following user!"
	end

	def destroy
		current_user.unfollow(user)
		redirect_to user, notice: "No longer following user!"
	end

	private
		def user
			@_user ||= User.find(params[:user_id])
		end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :check_logged_in_user

  def show
  end

  private
  	def check_logged_in_user
  	  if signed_in?
  	  	redirect_to dashboard_path
  	  end
  	end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
	def create
		content = build_content
		shout = current_user.shouts.build(content: content)

		unless shout.save
			flash.alert = 'Cannot shout!'
		end
		redirect_to dashboard_path
	end

	private
		def build_content
			temp = PhotoShout.new(photo_shout_params)
		end

		def photo_shout_params
			params.require(:photo_shout).permit(:image)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
	def show
		@shout = Shout.find(params[:id])
	end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
	def create
		content = build_content
		shout = current_user.shouts.build(content: content)

		unless shout.save
			flash.alert = 'Could not shout!'
		end
		redirect_to dashboard_path
	end

	private
		def build_content
			temp = TextShout.new(text_shout_params)
		end

		def text_shout_params
			params.require(:text_shout).permit(:body)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
	def gravatar user, size = 48
		digest = Digest::MD5.hexdigest(user.email)
		image_tag "http://gravatar.com/avatar/#{digest}?s=#{size}"
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def follow_button user
		if current_user.following? user
			button_to 'Unfollow', user_follow_path(user), method: 'delete'
		else
			button_to 'Follow', user_follow_path(user)			
		end		
	end
end

app/views/dashboards/show.html.erb
<%= form_for @dashboard.new_text_shout do |f| %>
	<%= f.text_field :body, placeholder: 'Shout here!' %>
	<%= f.submit 'Shout!' %>
<% end %>

<%= form_for @dashboard.new_photo_shout do |f| %>
	<%= f.file_field :image %>
	<%= f.submit 'Shout!' %>
<% end %>

<%= render @dashboard.timeline %>

app/views/homes/show.html.erb
Welcome to Shouter!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
	<% if signed_in? %>
	  <%= link_to current_user.username, dashboard_path %>
	  <%= link_to 'Sign out', session_path, method: :delete %>
	<% else %>
	  <%= link_to 'Sign in', new_session_path %>
	  <%= link_to 'Sign up', new_user_path %>
	<% end %>
</div>

<% if alert %>
	<p><%= alert %><p>
<% end %>
<% if notice %>
	<p><%= notice %><p>
<% end %>

<%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= link_to image_tag(photo_shout.image.url(:shout)), photo_shout.image.url %>

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
	<%= gravatar shout.user %>
	<%= link_to shout.user.username, shout.user %>
	shout
	<div>
		<%= render shout.content %>
		<%= link_to time_ago_in_words(shout.created_at), shout %>
	</div>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/timelines/_timeline.html.erb
<div class="timeline">
	<%= render timeline.shouts %>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<div><%= link_to user.username, user %></div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<%= follow_button @user %>
<%= render @shouts %>